### ISSUE TITLE
Kare oyunu soyutlamaları

### ISSUE THREAD

**Issue by cglhrm** [D-K-E/2d-html5-game#1]
Kare oyununun tekniğini aynı tutarak, duvarları ve kareyi şeklen değiştirerek basit ve deneyimsel bir oyun yaratma fikrim var. biraz uzak gelebilir ama hissiyat yaratması açısından ekteki son filmimden kare.

![inside the thought](https://user-images.githubusercontent.com/60849728/74105173-c9285100-4b9e-11ea-8f78-8d5cb79141c8.jpg)

**Comment by D-K-E** [comment]
Mesajini aldim kardes

**Comment by D-K-E** [comment]
Duvarlari neye degistirelim için bir issue açiyorum. Bir de kareyi neye degistirelim için bir issue açiyorum
