### ISSUE TITLE
ilk konuşma ve kabaca taslakları paylaşma

### ISSUE THREAD

**Issue by cglhrm** [D-K-E/2d-html5-game#2]
1. oyun soyutlamaları üzerine düşündüğüm üç çizimin fikrini paylaşmak.
2. animasyon tekniği ve programlanma tekniği üzerine konuşmak.
3. eğer bu üç fikir uygun değilse yeni fikir için deadline belirlemek

**Comment by D-K-E** [comment]
Yeni issuelara ayrildi, #5 , #6 , #7
