### ISSUE TITLE
eğer bu üç fikir uygun değilse yeni fikir için deadline belirlemek

### ISSUE THREAD

**Issue by D-K-E** [D-K-E/2d-html5-game#7]
eğer bu üç fikir uygun değilse yeni fikir için deadline belirlemek

**Comment by D-K-E** [comment]
ikinci dalgali adamli fikir uygun.

**Comment by cglhrm** [comment]
Dikey ekran.
Dalga yakalamaca oyunu.
Üstten gördüğümüz insanı (sağ, sol, yukarı, aşağı) tuşlarını kullanarak hareket ettirmek ve ona doğru gelen dalgalarla etkileşimini sağlamak.
insan dalgalara değdiği vakit dalgalardan ses çıkacak ve değdiği yerden dağılıp küçülecekler. 
dalgalar eşit aralık ve birkaç deformasyonla insanın üstüne gelmeye devam edecekler.
oyun ilerlerse insanın geldiği aşağıya kumsal yukarıya ise dalgaların hiç köpüklü olmadığı sırf mavi su eklenebilir.
